name: Privileged
description: You are @cobaltdata or they asked you directly to create an issue here. If not, check the other options. 👇
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in this project! 🚀

        If you are not @cobaltdata or they didn't ask you directly to create an issue here, please start the conversation in a [Question in GitHub Discussions](https://github.com/cobaltdata/) instead.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you are allowed to create an issue here.
      options:
        - label: I'm @cobaltdata or they asked me directly to create an issue here.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
